apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/consul-1/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/consul-2/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-3
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/consul-3/
